# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-25 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import markdownx.models
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='Ссылка')),
                ('content', markdownx.models.MarkdownxField(verbose_name='Содержание')),
                ('file', models.FileField(upload_to=pages.models.url_to_path, verbose_name='Файл с содержанием')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255, verbose_name='Шаблон для url сайта')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Селектор для заголовка')),
                ('content', models.TextField(blank=True, max_length=255, null=True, verbose_name='Селекторы для содержания')),
            ],
        ),
    ]
